name: Daily Logout (Mon/Tue/Wed/Fri at 18:00 Lagos)

on:
  schedule:
    # 17:00 UTC = 18:00 Africa/Lagos
    - cron: '0 17 * * 1,2,3,5'
  workflow_dispatch: {}

jobs:
  logout:
    runs-on: ubuntu-latest
    env:
      P4S_EMAIL: ${{ secrets.P4S_EMAIL }}
      P4S_PASSWORD: ${{ secrets.P4S_PASSWORD }}
      P4S_BASE_URL: ${{ secrets.P4S_BASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install bot deps
        working-directory: automation/p4s-bot
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Submit daily log before logout
        working-directory: automation/p4s-bot
        env:
          # Default comment and randomized report are handled in code. Optional overrides shown below.
          DAILY_LOG_COMMENT: 'AI update & Code improvement'
        run: node bot.js --action daily-log

      - name: Run logout bot
        working-directory: automation/p4s-bot
        run: node bot.js --action logout
