name: Daily Clock-In (Mon/Tue/Wed/Fri at 08:00 Lagos)

on:
  schedule:
    # 07:00 UTC = 08:00 Africa/Lagos
    - cron: '0 7 * * 1,2,3,5'
  workflow_dispatch: {}

jobs:
  clockin:
    runs-on: ubuntu-latest
    env:
      P4S_EMAIL: ${{ secrets.P4S_EMAIL }}
      P4S_PASSWORD: ${{ secrets.P4S_PASSWORD }}
      P4S_BASE_URL: ${{ secrets.P4S_BASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install bot deps
        working-directory: automation/p4s-bot
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Print current Africa/Lagos time
        run: |
          sudo apt-get update && sudo apt-get install -y tzdata >/dev/null 2>&1
          TZ=Africa/Lagos date '+%Y-%m-%d %H:%M:%S %Z'

      - name: Run clock-in bot
        working-directory: automation/p4s-bot
        run: node bot.js --action clock-in
      - name: Upload debug artifacts (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: p4s-artifacts-clockin
          path: automation/p4s-bot/*.png
          if-no-files-found: ignore
